# Generated by Django 4.0.2 on 2022-02-23 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=100)),
                ('office_latitude', models.FloatField()),
                ('office_longitude', models.FloatField()),
                ('profile_picture', models.ImageField(upload_to='client_pfps')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(upload_to='representative_pfps')),
            ],
        ),
        migrations.CreateModel(
            name='TargetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='target_product_images')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_latitude', models.FloatField()),
                ('outlet_longitude', models.FloatField()),
                ('outlet_name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('programs', models.ManyToManyField(to='crm.Program')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.representative')),
            ],
        ),
    ]
