# Generated by Django 4.0.2 on 2022-02-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplan',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.schedule'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='client_pfps'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='outlet_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='outlet_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='outlet_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='targetproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='client_email_or_phone_not_null'),
        ),
        migrations.AddConstraint(
            model_name='representative',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='representative_email_or_phone_not_null'),
        ),
        migrations.AddConstraint(
            model_name='targetproduct',
            constraint=models.CheckConstraint(check=models.Q(('price__isnull', False), ('price__gte', 0)), name='target_product_price_positive'),
        ),
    ]
