# Generated by Django 4.0.2 on 2022-02-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_client_email_alter_client_office_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='satuday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
