# Generated by Django 4.0.6 on 2022-07-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_representative_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='client_pfps'),
        ),
        migrations.AlterField(
            model_name='client',
            name='specialty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
