# Generated by Django 4.0.6 on 2022-07-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='office_latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='office_longitude',
        ),
        migrations.AddField(
            model_name='client',
            name='geolocation_url',
            field=models.URLField(null=True),
        ),
    ]
