# Generated by Django 4.0.6 on 2022-07-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_office_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='geolocation_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
